# Generated by Django 5.2.8 on 2026-01-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='link',
            field=models.URLField(blank=True, help_text='Link to app update (Play Store / App Store / direct).'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.TextField(help_text='The message to display in the app.'),
        ),
    ]
